In [1]:
import torch

print(torch.__version__)

2.5.1


# Intro to Tensors (Init, Create)

In [2]:
# Introdcution to Tensors
scalar = torch.tensor(10)  # creates a tensor
print("Scalar is:", scalar) # this will print tensor(10) and not just 10 --> meaning it is a scalar of type tensor
print("It is of dimension:", scalar.dim(), "and it is of value:", scalar.item()) # this will print 10 value here

Scalar is: tensor(10)
It is of dimension: 0 and it is of value: 10


In [3]:
vector = torch.tensor([10, 12, 39])  # creates a vector
print("Vector is:", vector) 
print("It is of dimension:", vector.dim(), "and it is of size:", vector.shape) 

Vector is: tensor([10, 12, 39])
It is of dimension: 1 and it is of size: torch.Size([3])


In [4]:
matrix = torch.tensor([[10, 12, 39] ,
                       [1, 2, 3]])  # creates a matrix
print("Matrix is:", matrix) 
print("It is of dimension:", matrix.dim(), "and it is of size:", matrix.shape)

Matrix is: tensor([[10, 12, 39],
        [ 1,  2,  3]])
It is of dimension: 2 and it is of size: torch.Size([2, 3])


In [5]:
matrix2 = torch.tensor([[[10, 12, 39] ,
                        [1, 2, 3]]])  # creates a tensor
print("Tensor is:", matrix2) 
print("It is of dimension:", matrix2.dim(), "and it is of size:", matrix2.shape) 

Tensor is: tensor([[[10, 12, 39],
         [ 1,  2,  3]]])
It is of dimension: 3 and it is of size: torch.Size([1, 2, 3])


In [6]:
random_tensor = torch.rand(2, 2) # creates a tensor of size 2x2 with random values
print("Random tensor is:", random_tensor)

zero_tensor = torch.zeros(2, 2) # creates a tensor of size 2x2 with zeros
print("Zero tensor is:", zero_tensor)

Random tensor is: tensor([[0.6206, 0.7652],
        [0.3230, 0.4535]])
Zero tensor is: tensor([[0., 0.],
        [0., 0.]])


In [7]:
random_tensor2 = torch.rand(3,5,4) # creates a tensor with 3 dimensions with 5 rows and 4 columns of values
# for example: 3 matrices of 5x4 which maybe represents an R,G,B (3 channels) of 5x4 pixels
print("Random tensor2 is:", random_tensor2)

random_tensor3 = torch.rand(size=(2,2,3))
print("Random tensor3 is:", random_tensor3)

Random tensor2 is: tensor([[[0.4050, 0.6377, 0.8448, 0.9980],
         [0.7323, 0.0336, 0.8581, 0.6762],
         [0.8620, 0.8461, 0.2270, 0.1963],
         [0.2829, 0.6320, 0.2315, 0.4880],
         [0.1290, 0.8659, 0.8678, 0.3309]],

        [[0.5148, 0.7644, 0.3558, 0.9824],
         [0.5459, 0.1211, 0.4200, 0.3406],
         [0.1848, 0.6491, 0.1335, 0.6436],
         [0.6975, 0.5814, 0.6339, 0.0825],
         [0.1978, 0.3898, 0.6627, 0.3051]],

        [[0.0302, 0.0229, 0.8528, 0.4592],
         [0.5201, 0.8678, 0.2287, 0.1659],
         [0.5152, 0.5466, 0.8060, 0.7313],
         [0.4603, 0.1273, 0.6549, 0.5717],
         [0.3521, 0.1438, 0.0766, 0.1871]]])
Random tensor3 is: tensor([[[0.1525, 0.8348, 0.2500],
         [0.1696, 0.1499, 0.2295]],

        [[0.9180, 0.9137, 0.9531],
         [0.0212, 0.0346, 0.6324]]])


In [12]:
tensor_1 = torch.arange(0, 9, 2) # creates a tensor with values from 0 to 9 with step 2. includes 0 but not 9.
print("Tensor_1 is:", tensor_1) # use zeros_like, ones_like(name_of_tensor) to create a tensor of same size with zeros or ones
tensor_2 = torch.arange(0, 4).reshape(2, 2) # creates a tensor with values from 0 to 9 with step 2 and reshapes it to 2x2
print("Tensor_2 is:", tensor_2)
tensor_2.type()

Tensor_1 is: tensor([0, 2, 4, 6, 8])
Tensor_2 is: tensor([[0, 1],
        [2, 3]])


'torch.LongTensor'

# Tensor Attributes
Common errors with PyTorch tensor attributes:
- Some operations with mixing datatypes run error (tensor.dtype)
- When different shapes are getting multiplied or subjected to some operations (tensor.shape)
- Device is different: problem when you have multiple computation. (tensor.device)

In [ ]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32) # creates a tensor of type int32
print("Int_32_tensor is:", int_32_tensor)
# float_32_tensor = torch.tensor([1, 2, 3], dtype=torch.float32) # creates a tensor of type float32. No error and operation works fine.
float_32_tensor = torch.tensor([1, 2], dtype=torch.float32) # gives "a size of tensor a must match size of tensor b" at dimension error
print("Float_32_tensor is:", float_32_tensor)
print(float_32_tensor* int_32_tensor) # performs element-wise multiplication and works also.

Int_32_tensor is: tensor([1, 2, 3], dtype=torch.int32)
Float_32_tensor is: tensor([1., 2.])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [ ]:
# https://stackoverflow.com/questions/76171206/pytorch-runtimeerror-check-uniform-bounds-not-implemented-for-int
# tensor_3 = torch.rand(3,4, dtype= torch.int16) # throws "check uniform bounds" error as only float can be initialized with random values
tensor_3 = torch.rand(3,4, dtype= torch.float16) # default is float32
print("Shape of tensor_3 is:", tensor_3.shape)
print("Datatype of tensor_3 is:", tensor_3.dtype)
print("Device of tensor_3 is:", tensor_3.device)



Shape of tensor_3 is: torch.Size([3, 4])
Datatype of tensor_3 is: torch.float16
Device of tensor_3 is: cpu


# Manipulating Tensors
- Basic arithmetic operations (+, -, /, *)
- Matrix Multiplication (dot product)

2 main rules of matmul:
@ another symbol for matmul or .
1. Inner dimensions must match: (3,2) @ (3,2) won't work. (3,2) @ (2,3)
2. Resulting shape is outer-dimensions basically

Neural Networks basically make use of these operations to represent the model and represent data for the mathematical functions involved.

In [ ]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_32_tensor = torch.tensor([1, 2, 3], dtype=torch.float32) 

product = int_32_tensor * float_32_tensor  # throws error if shapes are different.
# performs element-wise multiplication (needs same shape). or can be a scalar multiplied to vector/matrix
# For arithmetic operations, use symbols or torch.add, torch.sub etc.
print("Product is:", product)
print("Adding 10 to int_32_tensor:", int_32_tensor+10) # gives tensor([11, 12, 13], dtype=torch.int32)

Product is: tensor([1., 4., 9.])
Adding 10 to int_32_tensor: tensor([11, 12, 13], dtype=torch.int32)


In [ ]:
print(torch.matmul(torch.rand(2,3), torch.rand(3,2))) # matrix multiplication (dot product) of 2x3 and 3x2 matrices gives 2x2 matrix

# print(torch.matmul(int_32_tensor, float_32_tensor)) # gives errors and needs to be of same dtype
print(torch.matmul(int_32_tensor, int_32_tensor)) # works fine. Even though we didn't give any reshape, it took the transpose and multiplied correctly, the 2 matrices.
# This is because it takes this as just 3 and not (3,1)

tensor([[0.7146, 0.4627],
        [0.5713, 0.8185]])
tensor(14, dtype=torch.int32)


In [ ]:
# torch.matmul(torch.rand(2,3), torch.rand(2,3)) # won't work as inner dimensions don't match
torch.matmul(torch.rand(2,3), torch.rand(3,3))
torch.matmul(int_32_tensor, int_32_tensor)

torch.Size([3])

# Tensor Aggregation
- To find min, max, mean, sum etc. --> you have in-built functions for this in PyTorch

In [ ]:
tensor_agg = torch.arange(0,100)
print(torch.min(tensor_agg))
print(torch.max(tensor_agg))
print(torch.mean(tensor_agg.type(torch.float32)))   # needs to be float always.
torch.sum(tensor_agg), tensor_agg.sum()
print(torch.argmin(tensor_agg))  # gives index of min value. i.e., shows where the min value in the tensor is located.
print(torch.argmax(tensor_agg))  # gives index of max value. These are particularly useful with softmax for classification problems.

tensor(0)
tensor(99)
tensor(49.5000)
tensor(0)
tensor(99)


# Reshaping Tensors
- Reshape an input tensor to a particular shape
- Stack combines/concatenates along a particular dimension (hstack/vstack also exists)
- Squeeze removes all 1 dimensions from a tensor and unsqueeze does the opposite

In [ ]:
s = torch.arange(1,10).reshape(3,3)
print(s, s.shape)

s_reshape = s.reshape(1,9)  # returns a new tensor and does not change the original tensor s
# just s.reshape doesn't change anything.
print(s_reshape, s_reshape.shape)

# s_stack = torch.stack([s,s], dim=0) # stacks s on top of itslef along the dimension 0, which is why we have 2 times 3x3 tensor.
# s_stack = torch.stack([s,s], dim=1) # gives 3,2,3 tensor, each rows stacked now.
# s_stack = torch.stack([s,s], dim=2) # gives 3,3,2 with column stacking.
s_stack = torch.hstack([s,s]) # gives 3,6 tensor by horizontal stack. Increased number of columns.
print(s_stack, s_stack.shape)

s_squeeze = torch.squeeze(s_reshape)  # removes all single dimensions i.e., 1
print(s_squeeze, s_squeeze.shape)  # changed from 1x9 to 9
# s_permute = torch.permute(s_stack, (0,1) ) # will keep same
s_permute = torch.permute(s_stack, (1,0) ) # changed to 6x3. here we changed the 0 dimension to 1st and 1st to 0 i.e., transpose
# this can be used to mix dimensions when needed. typically used with image tensors
print(s_permute, s_permute.shape)
# also works with tensor.permute and so on. 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]]) torch.Size([3, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9],
        [1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]) torch.Size([6, 3])


# Selecting data from Tensors
- Indexing is similar to NumPy

In [ ]:
x = torch.arange(1,51).reshape(2, 5,5)
print(x)

# indexing on x
print("First element:", x[0][0]) # gives 1,2,3,4,5 i.e. this gives the first row of the first 5x5 matrix
print("First element:", x[1][0]) # gives 26-30 i.e. this gives the first row of the second 5x5 matrix
print("Randome element:", x[1][2][2]) # should give 38 and it did

# to select all values of a particular dimension and specific index in other dimensions:
print("Test:", x[:, 2, 3]) # returns 3rd row 4 th column from all 0-dimensions. (2 0-dimension elements here)
print("Test 2:", x[0, :, 3]) # returns all rows from first 5x5 matrix at 4th column

# test yourself: return the 2nd column from both matrices in the tensor. i.e. all row items is needed for the 2nd column 
print("Test 3:", x[:,1,:] ) # returns rows
print("Test 4:", x[:, :,1], x[:,:,1].shape ) # returns columns. the correct answer. selects only 2nd column but : means all other rows and tensor dimensions are considered 
# shape here should be 2,5,1 or just 2,5 

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25]],

        [[26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40],
         [41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50]]])
First element: tensor([1, 2, 3, 4, 5])
First element: tensor([26, 27, 28, 29, 30])
Randome element: tensor(38)
Test: tensor([14, 39])
Test 2: tensor([ 4,  9, 14, 19, 24])
Test 3: tensor([[ 6,  7,  8,  9, 10],
        [31, 32, 33, 34, 35]])
Test 4: tensor([[ 2,  7, 12, 17, 22],
        [27, 32, 37, 42, 47]]) torch.Size([2, 5])


In [ ]:
# reproducibility with random numbers. pseudo-random numbers generator with Mersenne Twister algorithm.
torch.manual_seed(42) # you can set at the beginning of a program. But in ipynb it needs to be set before every random function call to get same results
print(torch.rand(3,4)) # provides the same random numbers every time
# if you set the seed again, it will give the same random numbers again
print(torch.rand(3,4)) # provides a different set of random numbers now

# 42 is used as a movie reference from "The Hitchhiker's Guide to the Galaxy" where 42 is the answer to life, universe and everything.

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


# Exercises

- Create a random tensor with shape (7, 7).
- Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
- Set the random seed to 0 and do exercises 2 & 3 over again.
- Find the maximum and minimum values of the matrix multiplication.
- Find the maximum and minimum index values of the output of matrix multiplication.
- Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
# Create a random tensor with shape (7, 7).
ex_random_tensor = torch.rand(7,7)
print("Exercise random tensor:", ex_random_tensor) # here, because random seed is not set, it gives different values every time.

# Matrix multiplication
ex_random_tensor_2 = torch.rand(1,7)
# matrix_mult = torch.matmul(ex_random_tensor, ex_random_tensor_2) # directly (7,7 and 1,7)
matrix_mult = torch.matmul(ex_random_tensor, ex_random_tensor_2.T)
print(matrix_mult, matrix_mult.shape) # output 7,1. again random every time.

Exercise random tensor: tensor([[0.2539, 0.2956, 0.3413, 0.0248, 0.9103, 0.9192, 0.4216],
        [0.4431, 0.2959, 0.0485, 0.0134, 0.6858, 0.2255, 0.1786],
        [0.4610, 0.3335, 0.3382, 0.5161, 0.3939, 0.3278, 0.2606],
        [0.0931, 0.9193, 0.2999, 0.6325, 0.3265, 0.5406, 0.9662],
        [0.7304, 0.0667, 0.6985, 0.9746, 0.6315, 0.8352, 0.9929],
        [0.4234, 0.6038, 0.1525, 0.3970, 0.8703, 0.7563, 0.1836],
        [0.0991, 0.1583, 0.0066, 0.1142, 0.3764, 0.8374, 0.5837]])
tensor([[1.5107],
        [0.6358],
        [0.8928],
        [1.2103],
        [1.9033],
        [1.2658],
        [0.9884]]) torch.Size([7, 1])


In [50]:
# exercise 4
torch.manual_seed(0) # set seed to 0

# Create a random tensor with shape (7, 7).
ex_random_tensor = torch.rand(7,7)
print("Exercise random tensor:", ex_random_tensor) # here, because random seed is set, it gives same values every time.

# Matrix multiplication
ex_random_tensor_2 = torch.rand(1,7)
# matrix_mult = torch.matmul(ex_random_tensor, ex_random_tensor_2) # directly (7,7 and 1,7)
matrix_mult = torch.matmul(ex_random_tensor, ex_random_tensor_2.T)
print(matrix_mult, matrix_mult.shape) # output 7,1. but same every time.

# exercise for min max  of matrix_mult and their indices.

print("Max value:", torch.max(matrix_mult), "at", torch.argmax(matrix_mult))
print("Min value:", torch.min(matrix_mult), "at", torch.argmin(matrix_mult))

Exercise random tensor: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])
Max value: tensor(3.0481) at tensor(3)
Min value: tensor(1.7067) at tensor(4)


In [51]:
torch.manual_seed(7)
ex_rand_tensor_3 = torch.rand(1,1,1,10)
print("Exercise random tensor 3:", ex_rand_tensor_3, ex_rand_tensor_3.shape)
ex_rand_tensor_3_squeezed = torch.squeeze(ex_rand_tensor_3)
print("Exercise random tensor 3 squeezed:", ex_rand_tensor_3_squeezed, ex_rand_tensor_3_squeezed.shape)

Exercise random tensor 3: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
Exercise random tensor 3 squeezed: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
